koseven/koseven

_config.yml

Worked in my local environment

Add Download-Links to header

---

modules/minion/classes/Kohana/Minion/Exception.php

Minion exception is now compatible with Kohana_Kohana_Exception

Minion update

---

modules/userguide/classes/Kohana/Kodoc/Markdown.php

Fixes “[] operator not supported for strings”.

Switched variable declaration from string to array.

---

modules/database/config/database.php

default type changed to MySQLi

Default type "MySQLi"

---

.gitignore
composer.json

From the suggestion on #36
Comments below.

Add composer definition and .gitignore.

---

modules/image/classes/Kohana/Image.php
modules/image/classes/Kohana/Image/GD.php
modules/image/classes/Kohana/Image/Imagick.php

Support for webp format in image module

---

modules/image/classes/Kohana/Image.php

Fixed const type in Image module

---

system/classes/Kohana/Core.php

Check PHP before reading deprecated safe_mode and register_globals

---

modules/pagination/classes/kohana/pagination.php

Adds the params for controller and action to the route params in pagination for routes with variable params.

Fix #59: pagination controller and action.

---

modules/cache/tests/cache/CacheTest.php
modules/unittest/bootstrap.php
modules/unittest/classes/Kohana/Unittest/TestCase.php
modules/unittest/classes/Kohana/Unittest/TestSuite.php
system/tests/kohana/Config/GroupTest.php
system/tests/kohana/ConfigTest.php
system/tests/kohana/ResponseTest.php
system/tests/kohana/RouteTest.php
system/tests/kohana/UploadTest.php
system/tests/kohana/ValidationTest.php
system/tests/kohana/request/client/ExternalTest.php
system/tests/kohana/request/client/InternalTest.php

This PR fixes unittest issues in phpunit 6.0.8 in Issue https://github.com/koseven/koseven/issues/64

Unittest fix

---

system/classes/Kohana/URL.php

Okay, this surely has to be tested.

#19 Subdomains - add subdomain in URL::site

---

application/bootstrap.php

This will help beginners easily include additional libraries in their project

Added example for enable composer libraries

---

README.md

Users should see a list of changes ;)

Replaced download link

---

system/config/curl.php

Updated cURL useragent header

---

system/classes/Kohana/Core.php
system/classes/Kohana/Log/File.php

Insulation system files

---

modules/encrypt/classes/Kohana/Encrypt.php
modules/encrypt/classes/Kohana/Encrypt/Engine.php
modules/encrypt/classes/Kohana/Encrypt/Engine/Openssl.php
modules/encrypt/config/encrypt.php

Reduction to Kohana-codestyle

---

system/classes/Kohana/URL.php

Fix #117.
Changes are tested on the production server

Using link anchors + ASCII (bugfix)

---

system/classes/Kohana/Response.php

Change from spaces to tabs to keep with Koseven formatting guidelines.

Fix formatting for #131

---

public/example_2.4.htaccess

Added Apache 2.4 .htaccess file example

Example .htaccess for Apache 2.4

---

system/guide/kohana/index.md

Unofficial wiki is dead.
Added Telegram group link.
New URL for license and issues.

Updated documentation links

---

README.md

What about new logo in our README?
Now we have nice logo and we can use it.

New README logo

---

public/install.php

New install page without mcrypt

---

modules/database/classes/Kohana/Database/Query/Builder.php

Fixed preparing SQL query for the IN condition

---

system/classes/Kohana/HTTP/Request.php

Adds missing Request::PATCH constant in Request method types

Request::PATCH

---

system/guide/kohana/mvc/models.md

Improve documentation

---

system/classes/Kohana/Request.php
system/tests/kohana/RequestTest.php

Also added test coverage for client_ip proxy types

Added Cloudflare support when detecting Request::$client_ip

---

CONTRIBUTING.md

via:
https://help.github.com/articles/configuring-a-remote-for-a-fork/

Updated command line for syncing fork w/ main repo

---

modules/auth/classes/Kohana/Auth/File.php
modules/database/classes/Kohana/Database/Query/Builder/Insert.php
modules/userguide/classes/Kohana/Kodoc/Property.php
modules/userguide/vendor/markdown/markdown.php
system/classes/Kohana/HTTP/Exception/405.php
system/classes/Kohana/HTTP/Header.php
system/classes/Kohana/Request.php
system/classes/Kohana/Request/Client/Curl.php
system/classes/Kohana/Request/Client/Internal.php

found using phpcs-variable-analysis

remove unused variables

---

README.md

Update master branch with README latest release

Latest release 3.3.9

---

system/views/kohana/error.php

According to https://github.com/koseven/koseven/issues/181

Updated error.php

---

system/classes/Kohana/View.php

… status code. Please review this, I'm open to suggestions.

halt script execution when exception occurs in view rendering

---

modules/orm/classes/Kohana/ORM.php

Update documentation of ORM::changed() to match implementation.

---

modules/minion/classes/Kohana/Minion/Exception.php
system/classes/Kohana/Kohana/Exception.php

Fixed error handlers (strict compliance with PHP 7)

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
CODE_OF_CONDUCT.md

Adding ISSUE Templates for Bugs and PR's
Also adding a Code of Conduct Page
What do you think?

Adding GitHub/Community Standard Files

---

modules/auth/config/userguide.php
modules/cache/classes/Cache/Memcached.php
modules/cache/classes/Kohana/Cache/Memcached.php
modules/cache/config/userguide.php
modules/codebench/config/userguide.php
modules/database/config/userguide.php
modules/encrypt/classes/Kohana/Encrypt.php
modules/encrypt/classes/Kohana/Encrypt/Engine.php
modules/encrypt/classes/Kohana/Encrypt/Engine/Mcrypt.php
modules/encrypt/classes/Kohana/Encrypt/Engine/Openssl.php
modules/minion/classes/Kohana/Minion/CLI.php
modules/minion/classes/Kohana/Minion/Exception.php
modules/minion/classes/Kohana/Minion/Exception/InvalidTask.php
modules/minion/classes/Kohana/Minion/Task.php
modules/orm/classes/Kohana/ORM/Behavior.php
modules/orm/classes/Kohana/ORM/Behavior/LocalBehavior.php
modules/orm/classes/ORM/Behavior/Guid.php
modules/orm/classes/ORM/Behavior/Slug.php
modules/orm/config/userguide.php
modules/unittest/classes/Kohana/Unittest/Database/TestCase.php
modules/unittest/classes/Kohana/Unittest/Helpers.php
modules/unittest/classes/Kohana/Unittest/TestCase.php
modules/unittest/classes/Kohana/Unittest/TestSuite.php
modules/userguide/classes/Kohana/Controller/Userguide.php
modules/userguide/classes/Kohana/Kodoc/Method.php
modules/userguide/classes/Kohana/Kodoc/Missing.php
system/classes/Kohana/Core.php
system/classes/Kohana/Valid.php
system/tests/kohana/CoreTest.php

Merging already released 3.3.9 Tag into master.
I will merge this without review, since those changes already got reviewed an are already published.

Merging 3.3.9 into master

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md
CODE_OF_CONDUCT.md

Since master is now default branch i am merging the templates into master

Merging Templates from devel

---

modules/database/classes/Kohana/Database/Query/Builder.php

See #323 
Please review and if correct merge asap.

Add check to order_by clause

---

modules/database/classes/KO7/Database/Query/Builder.php

Already approved in PR #324, just merging this into devel branch

Fixing Issue #323

---

modules/minion/classes/Kohana/Minion/CLI.php
modules/minion/classes/Kohana/Minion/Task.php
modules/minion/guide/minion/cli.md
modules/minion/guide/minion/menu.md
modules/minion/guide/minion/setup.md
modules/minion/guide/minion/tasks.md
modules/minion/tests/minion/TaskTest.php

Create correct urls in minion scripts based on the domain name
Add an additional function in minion module which should be called before using the urls.
Configuration can be done using the site config file or as a function argument.
#327 
Added unit tests.

Urls for minion

---

.travis.yml
composer.json

Update composer.json Description to new one (matching website). 
Update required PHP Version to > 7.3 (according to our [Roadmap](https://github.com/koseven/koseven/blob/devel/ROADMAP.md) for 4.0)
Replace old Forum Link (Telegram) with actual Forum Link (Discourse)

Composer Update

---

CHANGELOG.md
modules/unittest/bootstrap.php
public/index.php

Adding a constant for the Koseven `public` folder.
#330

Add PUBPATH constant

---

.coveralls.yml
.travis.yml
Dockerfile
composer.json

As described [here](https://github.com/koseven/koseven/pull/367#issuecomment-513498504)
It is easier and more clean to move to a dockerfile system instead travis native

Move travis native to docker

---

system/classes/Kohana/Route.php

This should be mixed because is not an array type param.

Wrong type of param

---

system/classes/KO7/Config/File/Reader.php

- Added prefix to loaded group to #409 
- Updated comments
- Added "soft" method typing
- Other small fixes

Bugfix: KO7_Config_File_Reader #409

---

modules/cache/classes/Kohana/Cache/Sqlite.php
modules/database/classes/Kohana/Database/Result.php
modules/database/classes/Kohana/Session/Database.php
modules/orm/classes/Kohana/ORM/Behavior/LocalBehavior.php
modules/orm/classes/Model/Auth/User/Token.php
modules/orm/classes/ORM/Behavior/Guid.php
modules/orm/classes/ORM/Behavior/Slug.php
system/classes/Kohana/Arr.php
system/classes/Kohana/Feed.php
system/classes/Kohana/Text.php

- Improves the randomness for text, session id's and uuid's
- Removes error level switches.
- Some small style changes
- mt_rand or rand where replaces with random_int to generate cryptographically secure pseudo-random integers
- removed error_reporting switches and replaced them with the `@` error control operator
- replaced spaces to tabs to comply with coding styles
Tested in working Koseven application, there are no changes that would affect normal operation.

Improved randomness and possible information leaks

---

system/classes/Kohana/Response.php

adding missing codes https://en.wikipedia.org/wiki/List_of_HTTP_status_codes

adding missing codes

---

modules/userguide/classes/KO7/Kodoc/Markdown.php
modules/userguide/vendor/markdown/markdown.php

Update userguide module to be PHP 7.4/8 compatible.
{} -> [] changes.
Verified the guide loaded on my local site.

PHP 7.4/8 changes for the userguide

---

system/classes/KO7/Debug.php

Remove repeated/deprecated code in `KO7_Debug::_dump()`
Update comments for `KO7_Debug::_dump()` and `KO7_Debug::trace()`

Update class KO7_Debug

---

system/classes/Kohana/Route.php

Update PhpDoc for method `Route::filter()`.
Fix parameter types.
- [x ] I have updated the documentation accordingly.

Update PhpDoc for Route::filter()

---

system/classes/Kohana/Arr.php

Fix for #472
Tested in multiple production projects

fix for #472 - Arr::path check for type

---

modules/database/classes/Kohana/Database/MySQLi/Result.php

PHP 8.1 compatibility

---

system/classes/Kohana/Cookie.php

Fix deprecated values in cookie class.
Made this work out of the box without breaking backward compatibility.
Partial fix for #471 
Tested in development.

fix deprecated cookie values

---

system/classes/Kohana/Route.php

8.1 compatibility

---

modules/userguide/classes/Kohana/Kodoc/Markdown.php
modules/userguide/vendor/markdown/markdown.php

Curly brace access deprecated since PHP 7.4

---

modules/userguide/classes/Kohana/Kodoc/Markdown.php
modules/userguide/vendor/markdown/markdown.php
modules/userguide/views/userguide/api/class.php

The <tt> tag is deprecated

---

modules/userguide/classes/Kohana/Kodoc/Markdown.php
modules/userguide/vendor/markdown/markdown.php
modules/userguide/views/userguide/api/class.php
system/classes/Kohana/Kohana/Exception.php

Undefined constant 'InvalidArgumentException'

---

modules/codebench/classes/Bench/ValidURL.php
modules/userguide/classes/Kohana/Kodoc/Markdown.php
modules/userguide/vendor/markdown/markdown.php
modules/userguide/views/userguide/api/class.php
system/classes/Kohana/Kohana/Exception.php

Explicit usage of FILTER_FLAG_HOST_REQUIRED deprecated

---

modules/database/classes/Kohana/Session/Database.php
system/classes/Kohana/Security.php

Fixing uniqid arguments for PHP 8

Fix uniqid() arguments

---

system/classes/Kohana/Valid.php

Valid::numeric local independent

---

system/classes/Kohana/UTF8.php

UTF8 8.1 compatibility

---

README.md

Update README.md: fixed dead link
